### PR TITLE
Adds basic logging example

### PR DESCRIPTION
**Pull request by friedbrice**
Addresses issue https://github.com/typeclasses/haskell-phrasebook/issues/15

This is perhaps already too complicated and it doesn't even get to concurrency or application architecture.

### CODE REVIEW

**Comment by chris-martin** [comment]
Sorry sorry I've been neglecting the Phrasebook :grimacing:

I'm fiddling around with this code now, but initial thoughts:

I think the Log type with multiple kinds of logs will come across well to Java users with an impulse for a log "interface". The log monoid is clever and I don't think it's too complicated. Using only the console log at first, while reading the config for the fancier log, nicely motivates why we would want such "log combinators".

**Comment by chris-martin** [comment]
I'm thinking of reading the file paths from environment variables instead of `getLine`, just because the interactivity is a little harder to demo.

**Comment by dbricehg** [comment]
I agree. I'll patch this tonight.

**Comment by friedbrice** [comment]
I agree. I'll patch this tonight.

**Comment by friedbrice** [comment]
I made a huge mistake and deleted my original fork. This PR is pickup up in https://github.com/typeclasses/haskell-phrasebook/pull/39

**Pull request closed without merging**
